### ISSUE TITLE
Need update for Symfony4 support

### ISSUE THREAD

**Issue by LordPato** [Nordeus/CrowdUserBundle#1]
As it is right now. When trying to install in Symfony4 you have the following composer error : 

Problem 1
    - Installation request for nordeus/crowd-user-bundle dev-master -> satisfiable by nordeus/crowd-user-bundle[dev-master].
    - nordeus/crowd-user-bundle dev-master requires sensio/framework-extra-bundle ~3.0,>=3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.

**Comment by djcvijic** [comment]
Hi @LordPato 

After switching to the newest version of Symfony (4.0.11 as of writing this), and running composer update, I am not observing the same error as you. All requirements are satisfied, and composer installs both symfony/symfony 4.0.11 and sensio/framework-extra-bundle 3.0.27 successfully.

I must assume your composer file is implicitly or explicitly requesting a version of framework-extra-bundle with major version above 3, but I cannot provide more assistance without seeing your whole composer.json file.

Also note that this bundle has not been tested with Symfony 4 and may not be fully compatible, so please use it with caution and report any incompatibilities.

**Comment by djcvijic** [comment]
CrowdUserBundle v2.0 is developed specifically for Symfony ^4.0. It also requires sensio/framework-extra-bundle ^5.0, so any remaining issues should be fixed now.
